name: Prepare Actions Env
runs:
  using: "composite"
  steps:
    - name: Send notification to Slack
      shell: bash
      run: curl -X POST --data-urlencode 'payload={"channel":"#alarm_test","username":"${{ github.event.repository.name }}","text":"Starting `${{ github.workflow }}` by *${{ github.actor }}*.\n${{ github.event.head_commit.url }}"}' https://hooks.slack.com/services/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
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 14
    - name: Setup cache
      uses: actions/cache@v4
      with:
        path: node_modules
        key: node_modules
        restore-keys: node_modules
    - name: Install dependeicies
      shell: bash
      run: yarn
