name: deploy_testing

concurrency:
  group: testing
  cancel-in-progress: true
  
on:
  workflow_dispatch:

jobs:
  build_testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Prepare Actions Env
        uses: ./.github/actions/prepare-actions-env
      - name: Configure
        shell: bash
        run: |
          cat > "src/config/config.json" << "EOF"
            ${{ vars.CONFIG_TESTING }}
          EOF
      - name: Build and Upload Artifact
        uses: ./.github/actions/build-and-upload-artifact
      
  deploy_testing:
    runs-on: ubuntu-latest
    needs: build_testing
    environment: testing
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Prepare Actions Env
        uses: ./.github/actions/prepare-actions-env
      - name: Download Artifact and Deploy
        uses: ./.github/actions/download-artifact-and-deploy
        with:
          firebase_token: ${{ secrets.FIREBASE_TOKEN }}
          firebase_project: foospace-freezone-testing
