name: deploy_dev

concurrency:
  group: dev
  cancel-in-progress: true
  
on: push

jobs:
  build_dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
 
      
  deploy_dev:
    runs-on: ubuntu-latest
    needs: build_dev
    environment: dev
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
 
