name: lint

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification to Slack
        shell: bash
        run: curl -X POST --data-urlencode 'payload={"channel":"#alarm_test","username":"Github Notification","text":"${{ github.ref.GITHUB_ACTION }}\n${{ github.event.head_commit.url }}."}' https://hooks.slack.com/services/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
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Prepare Actions Env
        uses: ./.github/actions/prepare-actions-env
      - run: yarn lint
